# Práctica 2

**Mateo Zariquiey Pérez     100522396**

**Héctor Fuertes Muñoz      100522401**

## 1. Introducción y objetivos

En esta práctica se trate un problema de **aprendizaje no supervisado**, cuyo objetivo es identificar los posibles patrones y agrupaciones presentese un dataset  sin disponer de etiquetas previas. A diferencia de un aprendizaje supervisado, en este caso no se parte de una variable objetivo conocida, sino que se explora la estructura interna de los datos a partir de las relaciones y similitudes que presentan entre sus atributos.

Por lo tanto, en esta práctica se trabajará con un dataset formado por las características de distintas estrellas, que será la base utilizada para aplicar las técnicas de **clustering**. El análisis se dividirá en:
+ Transformaciónd e los datos.
+ Reducción de dimensionalidad (PCA).
+ Aplicación de los distintos algoritmos de clustering.

También se estudiará como la representación de los datos influye en la capacidad de los algoritmos para detectar distinitas agrupaciones.

A lo largo de la práctica se utilizarán varimos métodos de clustering con la finalidad de comaprar sus comportamientos, analizar los resultados y valorar cual es el más adecuado para este caso.

## 2. Carga del dataset

En esta sección se realiza la carga del dataset para la práctica. Además se establece la configuración inicial del entorno. En nuestro caso se fija la semilla con el NIA: 100522401 tal y como indica en el enunciado de la práctica.

In [ ]:
# imports básicos
import numpy as np
import pandas as pd

# Se establece la semilla
SEED = 100522401
np.random.seed(SEED)

# Carga del dataset
df = pd.read_csv('../data/stars_data.csv')

df.head()
print("\nDataset cargado correctamente")

   Temperature         L       R    A_M Color Spectral_Class
0         3068  0.002400  0.1700  16.12   Red              M
1         3042  0.000500  0.1542  16.60   Red              M
2         2600  0.000300  0.1020  18.70   Red              M
3         2800  0.000200  0.1600  16.65   Red              M
4         1939  0.000138  0.1030  20.06   Red              M

## 3. EDA

En este apartado se realiza un análisis exploratorio de los datos o **EDA**. En problemas de aprendizaje no supervisado, esta dase es crucial ya que la calidad de los resultados obtenidos depende en gran medida de cómo estén representados los datos y de si existen diferencias de escalado, valores atípicos o inconsistencias en las variables categóricas. 

Entonces, esta sección se analizará:
* Estructura general del conjunto de datos
* Distribución de variables numéricas.
* Revisión de la escala y rango de las variables.
* Valores faltantes y duplicados.
* Posibles columnas id.
* Valores atípicos.
* Valores presentes en las variables categóricas.
* Análisis básico de las relaciones entre variables numéricas.

## 3.1 Estructura general del conjunto de datos
A continuación se realiza una primera inspección general del dataset con el objetivo de conocer su estructura básica. Antes de omenzar con un análisis más detallado, es conveniente revisar las variables disponibles, que tipo de dato maneja cada una y el número de observaciones que tienen.

In [8]:
# DImensión del dataset
print("Dimensión del dataset")
print(df.shape)

# Columnas
print("\nNombre de las columnas:")
print(df.columns.tolist())

# Rows
print("\nPrimeras filas del dataset")
display(df.head())

# Información general del dataset
print("\nInformación general del dataset")
df.info()

# Tipos de datos
print("\nTipos de datos por columna")
display(df.dtypes)

Dimensión del dataset
(240, 6)

Nombre de las columnas:
['Temperature', 'L', 'R', 'A_M', 'Color', 'Spectral_Class']

Primeras filas del dataset

   Temperature         L       R    A_M Color Spectral_Class
0         3068  0.002400  0.1700  16.12   Red              M
1         3042  0.000500  0.1542  16.60   Red              M
2         2600  0.000300  0.1020  18.70   Red              M
3         2800  0.000200  0.1600  16.65   Red              M
4         1939  0.000138  0.1030  20.06   Red              M

Información general del dataset
<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Temperature     240 non-null    int64
 1   L               240 non-null    float64
 2   R               240 non-null    float64
 3   A_M             240 non-null    float64
 4   Color           240 non-null    str
 5   Spectral_Class  240 non-null    str
dtypes: float64(3), int64(1), str(2)
memory usage: 11.4 KB

Tipos de datos por columna

Temperature         int64
L                 float64
R                 float64
A_M               float64
Color                 str
Spectral_Class        str
dtype: object